usethis::use_package("biomaRt")
usethis::use_package("Matrix")
usethis::use_package("GEOquery")
usethis::use_package("matrixStats")
usethis::use_package("SingleCellExperiment")
usethis::use_package("scDblFinder")
usethis::use_package("scds")
usethis::use_package("Seurat")
# usethis::use_package("GEOquery")